apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: cdc-sql-dim-back-account
  namespace: cdc
spec:
  # Image vừa build ở trên
  image: ghostwood/flink-mbs:1.0.9

  # Version Flink tương ứng với image (1.18.x -> v1_18)
  flinkVersion: v1_18

  serviceAccount: flink   # SA mà bạn đã dùng cho operator

  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    state.backend: rocksdb
    state.checkpoints.dir: s3a://warehouse/dim_back_account/checkpoints
    state.savepoints.dir:  s3a://warehouse/dim_back_account/savepoints
    execution.checkpointing.interval: "60s"
    fs.s3a.endpoint: "http://minio.storage.svc.cluster.local:9000"
    fs.s3a.access.key: "minioadmin"
    fs.s3a.secret.key: "minio@demo!"
    fs.s3a.path.style.access: "true"
    fs.s3a.connection.ssl.enabled: "false"


  jobManager:
    resource:
      cpu: 1
      memory: "1024m"
  taskManager:
    resource:
      cpu: 2
      memory: "2048m"

  job:
    jarURI: local:///opt/flink/lib/cdc-kafka-starrocks-1.0-SNAPSHOT.jar
    entryClass: org.mbs.DimBackAccount
    parallelism: 2
    upgradeMode: savepoint  
