CREATE TABLE default_catalog.mbs_realtime_db.fact_t_back_advance_withdraw (
  `PK_ADVANCE_WITHDRAW` varchar(1048576),
  `partition_date` date,
  `C_MARKET` varchar(1048576) DEFAULT NULL,
  `C_WITHDRAW_DATE` datetime DEFAULT NULL,
  `C_CREATOR_BRANCH_CODE` varchar(1048576) DEFAULT NULL,
  `C_CREATOR_SUB_BRANCH_CODE` varchar(1048576) DEFAULT NULL,
  `C_CREATOR_CODE` varchar(1048576) DEFAULT NULL,
  `C_CREATE_TIME` datetime DEFAULT NULL,
  `C_APPROVER_CODE` varchar(1048576) DEFAULT NULL,
  `C_APPROVE_TIME` datetime DEFAULT NULL,
  `C_ACCOUNT_CODE` varchar(1048576) DEFAULT NULL,
  `C_ACCOUNT_TYPE` varchar(1048576) DEFAULT NULL,
  `C_ACCOUNT_NAME` varchar(1048576) DEFAULT NULL,
  `C_TRANSACTION_NO` varchar(1048576) DEFAULT NULL,
  `C_BANK_CODE` varchar(1048576) DEFAULT NULL,
  `C_SELL_DATE` datetime DEFAULT NULL,
  `C_DUE_DATE` datetime DEFAULT NULL,
  `C_FILE_NO` varchar(1048576) DEFAULT NULL,
  `C_CASH_VOLUME` decimal(38, 10) DEFAULT NULL,
  `C_FEE_RATE` decimal(38, 10) DEFAULT NULL,
  `C_FEE` decimal(38, 10) DEFAULT NULL,
  `C_CONTENT` varchar(1048576) DEFAULT NULL,
  `C_STATUS` varchar(1048576) DEFAULT NULL,
  `C_BANK_CODE_IN` varchar(1048576) DEFAULT NULL,
  `C_BRANCH_BANK_CODE` varchar(1048576) DEFAULT NULL,
  `C_BRANCH_BANK_NAME` varchar(1048576) DEFAULT NULL,
  `C_BY_CALL` decimal(38, 10) DEFAULT NULL,
  `C_FEE_CTG` decimal(38, 10) DEFAULT NULL,
  `C_FEE_TSC` decimal(38, 10) DEFAULT NULL,
  `C_FEE_MB` decimal(38, 10) DEFAULT NULL,
  `C_CHANNEL` varchar(1048576) DEFAULT NULL,
  `C_STATUS_PROCESS` varchar(1048576) DEFAULT NULL,
  `C_ATS_FLAG` decimal(38, 0) DEFAULT NULL,
  `C_ATS_BANK_ACCOUNT` varchar(1048576) DEFAULT NULL,
  `C_ATS_BANK` varchar(1048576) DEFAULT NULL,
  `C_AUTHOR_CERT_ID` varchar(1048576) DEFAULT NULL,
  `C_AUTHOR_NAME` varchar(1048576) DEFAULT NULL,
  `C_PARTNER_BRANCH_BANK_CODE` varchar(1048576) DEFAULT NULL,
  `C_AUTOADV_WITHDRAW` decimal(1, 0) DEFAULT NULL,
  `C_FEE_DAYS` decimal(38, 10) DEFAULT NULL,
  `valid_from` datetime DEFAULT NULL,
  `valid_to` datetime DEFAULT NULL,
  `is_current` boolean DEFAULT NULL
)
PRIMARY KEY (PK_ADVANCE_WITHDRAW, partition_date)
PARTITION BY (partition_date)
DISTRIBUTED BY HASH(PK_ADVANCE_WITHDRAW) BUCKETS 2
PROPERTIES (
    "replication_num" = "2"
)

CREATE TABLE default_catalog.mbs_realtime_db.fact_t_back_deal_history (
  `PK_DEAL` varchar(1048576),
  `partition_date` date,
  `FK_DEAL_ORIGIN` varchar(1048576) DEFAULT NULL,
  `C_MARKET` varchar(1048576) DEFAULT NULL,
  `C_TRADING_CENTER` varchar(1048576) DEFAULT NULL,
  `C_ORDER_NO` decimal(38, 10) DEFAULT NULL,
  `C_SUB_ORDER_NO` decimal(38, 10) DEFAULT NULL,
  `C_TRADER_BRANCH_CODE` varchar(1048576) DEFAULT NULL,
  `C_TRADER_SUB_BRANCH_CODE` varchar(1048576) DEFAULT NULL,
  `C_TRADER_CODE` varchar(1048576) DEFAULT NULL,
  `C_BROKER_BRANCH_CODE` varchar(1048576) DEFAULT NULL,
  `C_BROKER_SUB_BRANCH_CODE` varchar(1048576) DEFAULT NULL,
  `C_BROKER_CODE` varchar(1048576) DEFAULT NULL,
  `C_ACCOUNT_BRANCH_CODE` varchar(1048576) DEFAULT NULL,
  `C_ACCOUNT_SUB_BRANCH_CODE` varchar(1048576) DEFAULT NULL,
  `C_ACCOUNT_CODE` varchar(1048576) DEFAULT NULL,
  `C_ACCOUNT_TYPE` varchar(1048576) DEFAULT NULL,
  `C_SHARE_CODE` varchar(1048576) DEFAULT NULL,
  `C_SHARE_TYPE` varchar(1048576) DEFAULT NULL,
  `C_SHARE_STATUS` varchar(1048576) DEFAULT NULL,
  `C_SIDE` varchar(1048576) DEFAULT NULL,
  `C_SIDE_TYPE` varchar(1048576) DEFAULT NULL,
  `C_CHANEL` varchar(1048576) DEFAULT NULL,
  `C_TRANSACTION_NO` varchar(1048576) DEFAULT NULL,
  `C_TRANSACTION_DATE` datetime DEFAULT NULL,
  `C_DUEDAY` varchar(1048576) DEFAULT NULL,
  `C_DUE_DATE` datetime DEFAULT NULL,
  `C_MATCHED_VOLUME` decimal(38, 10) DEFAULT NULL,
  `C_MATCHED_PRICE` decimal(38, 10) DEFAULT NULL,
  `C_SHARE_COMM_GROUP` varchar(1048576) DEFAULT NULL,
  `C_COMM_PACKAGE` varchar(1048576) DEFAULT NULL,
  `C_COMM_RATE` decimal(38, 10) DEFAULT NULL,
  `C_TAX_FLAG` decimal(38, 10) DEFAULT NULL,
  `C_TAX_RATE` decimal(38, 10) DEFAULT NULL,
  `C_DEAL_STATUS` decimal(38, 10) DEFAULT NULL,
  `C_MATCHED_TIME` datetime DEFAULT NULL,
  `C_SET_ORDER_TYPE` varchar(1048576) DEFAULT NULL,
  `C_SUB_MARKETING_ID` varchar(1048576) DEFAULT NULL,
  `C_DEFAULT_PRIMARY_KEY` varchar(1048576) DEFAULT NULL,
  `C_CARE_PACKAGE` varchar(1048576) DEFAULT NULL,
  `C_CARE_RATE` decimal(38, 10) DEFAULT NULL,
  `C_ISIN_CODE` varchar(1048576) DEFAULT NULL,
  `C_MARKET_ID` varchar(1048576) DEFAULT NULL,
  `C_MARKET_SUBID` varchar(1048576) DEFAULT NULL,
  `C_KRX_ORDER_ID` varchar(1048576) DEFAULT NULL,
  `C_KRX_EXEC_ID` varchar(1048576) DEFAULT NULL,
  `C_KRX_CLORDID` varchar(1048576) DEFAULT NULL,
  `C_KRX_ORIG_CLORDID` varchar(1048576) DEFAULT NULL,
  `valid_from` datetime DEFAULT NULL,
  `valid_to` datetime DEFAULT NULL,
  `is_current` boolean DEFAULT NULL
)
PRIMARY KEY (PK_DEAL, partition_date)
PARTITION BY (partition_date)
DISTRIBUTED BY HASH(PK_DEAL) BUCKETS 8
PROPERTIES (
    "replication_num" = "2"
)

CREATE TABLE default_catalog.mbs_realtime_db.fact_t_tlo_debit_balance_history (
  `PK_TLO_DEBIT_BALANCE` varchar(1048576),
  `partition_date` date,
  `C_TRANSACTION_DATE` datetime DEFAULT NULL,
  `C_ACCOUNT_CODE` varchar(1048576) DEFAULT NULL,
  `C_CASH_BUY_T0` decimal(15, 0) DEFAULT NULL,
  `C_CASH_BUY_T1` decimal(15, 0) DEFAULT NULL,
  `C_CASH_BUY_T2` decimal(15, 0) DEFAULT NULL,
  `C_DELIVER_DATE` datetime DEFAULT NULL,
  `C_INTERM_RATE` decimal(15, 5) DEFAULT NULL,
  `C_INTERM_BALANCE` decimal(15, 0) DEFAULT NULL,
  `C_INTERM_CASH_OUT` decimal(15, 0) DEFAULT NULL,
  `C_CASH_OUT_TO_OUTTERM` decimal(15, 0) DEFAULT NULL,
  `C_INTERM_FEE` decimal(25, 10) DEFAULT NULL,
  `C_INTERM_FEE_IN` decimal(25, 10) DEFAULT NULL,
  `C_INTERM_FEE_OUT` decimal(25, 10) DEFAULT NULL,
  `C_FEE_OUT_TO_OUTTERM` decimal(25, 10) DEFAULT NULL,
  `C_FEE_OUT_TO_ENDMONTH` decimal(25, 10) DEFAULT NULL,
  `C_EXPIRE_DATE` datetime DEFAULT NULL,
  `C_OUTTERM_RATE` decimal(15, 5) DEFAULT NULL,
  `C_OUTTERM_BALANCE` decimal(15, 0) DEFAULT NULL,
  `C_OUTTERM_CASH_OUT` decimal(15, 0) DEFAULT NULL,
  `C_OUTTERM_FEE` decimal(25, 10) DEFAULT NULL,
  `C_OUTTERM_FEE_IN` decimal(25, 10) DEFAULT NULL,
  `C_OUTTERM_FEE_OUT` decimal(25, 10) DEFAULT NULL,
  `C_ENDMONTH_BALANCE` decimal(15, 0) DEFAULT NULL,
  `C_ENDMONTH_CASH_OUT` decimal(15, 0) DEFAULT NULL,
  `C_ENDMONTH_FEE` decimal(25, 10) DEFAULT NULL,
  `C_ENDMONTH_FEE_IN` decimal(25, 10) DEFAULT NULL,
  `C_ENDMONTH_FEE_OUT` decimal(25, 10) DEFAULT NULL,
  `C_DELIEVER_TYPE` varchar(1048576) DEFAULT NULL,
  `C_YEAR_FEE_RATE` decimal(15, 5) DEFAULT NULL,
  `C_YEAR_OUT_RATE` decimal(15, 5) DEFAULT NULL,
  `C_MARKETING_ID` varchar(1048576) DEFAULT NULL,
  `C_SUB_BRANCH_CODE` varchar(1048576) DEFAULT NULL,
  `C_BRANCH_CODE` varchar(1048576) DEFAULT NULL,
  `C_BANK_BRANCH_DELIVER` varchar(1048576) DEFAULT NULL,
  `C_DEBIT_TYPE` decimal(1, 0) DEFAULT NULL,
  `C_MB_PENALTY_FEE` decimal(15, 0) DEFAULT NULL,
  `C_MB_PENALTY_DEBIT` decimal(15, 0) DEFAULT NULL,
  `C_MBS_EXPIRE_DEBIT` decimal(15, 0) DEFAULT NULL,
  `C_MBS_EXPIRE_FEE` decimal(15, 0) DEFAULT NULL,
  `C_TLO_COL_1` decimal(15, 0) DEFAULT NULL,
  `C_TLO_COL_2` decimal(15, 0) DEFAULT NULL,
  `C_TLO_COL_3` decimal(15, 0) DEFAULT NULL,
  `C_TLO_COL_4` decimal(15, 0) DEFAULT NULL,
  `C_TLO_COL_5` decimal(15, 0) DEFAULT NULL,
  `C_TLO_COL_6` decimal(20, 5) DEFAULT NULL,
  `C_TLO_COL_7` decimal(20, 5) DEFAULT NULL,
  `C_TLO_COL_8` decimal(20, 5) DEFAULT NULL,
  `C_TLO_COL_9` decimal(20, 5) DEFAULT NULL,
  `C_TLO_COL_10` decimal(20, 5) DEFAULT NULL,
  `FK_TLO_CONTRACT` varchar(1048576) DEFAULT NULL,
  `C_BASE_YEAR_FEE` decimal(5, 0) DEFAULT NULL,
  `C_BANK_CODE` varchar(1048576) DEFAULT NULL,
  `C_MBS_RATE` decimal(15, 5) DEFAULT NULL,
  `C_MBS_FEE` decimal(15, 0) DEFAULT NULL,
  `C_MBS_FEE_IN` decimal(15, 0) DEFAULT NULL,
  `C_MBS_FEE_OUT` decimal(15, 0) DEFAULT NULL,
  `C_LD_CODE` varchar(1048576) DEFAULT NULL,
  `C_MBB_DEPARTMENT` varchar(1048576) DEFAULT NULL,
  `C_DELIVER_CODE` varchar(1048576) DEFAULT NULL,
  `FK_MD_CONTRACT` varchar(1048576) DEFAULT NULL,
  `valid_from` datetime DEFAULT NULL,
  `valid_to` datetime DEFAULT NULL,
  `is_current` boolean DEFAULT NULL
)
PRIMARY KEY (PK_TLO_DEBIT_BALANCE, partition_date)
PARTITION BY (partition_date)
DISTRIBUTED BY HASH(PK_TLO_DEBIT_BALANCE) BUCKETS 2
PROPERTIES (
    "replication_num" = "2"
)

CREATE TABLE default_catalog.mbs_realtime_db.fact_v_t_erc_monthly_detail (
  `PK_MONTHLY_DETAIL_ID` varchar(1048576),
   `partition_year` varchar(1048576),
  `partition_month` varchar(1048576),
  `C_MONTH` decimal(2, 0) DEFAULT NULL,
  `C_YEAR` decimal(4, 0) DEFAULT NULL,
  `C_CUSTOMER_CODE` varchar(1048576) DEFAULT NULL,
  `C_ORIGIN_ACCOUNT_CODE` varchar(1048576) DEFAULT NULL,
  `C_B_MATCHED_VALUE` decimal(20, 0) DEFAULT NULL,
  `C_B_REVENUE_NET` decimal(20, 0) DEFAULT NULL,
  `C_D_REVENUE_NET` decimal(20, 0) DEFAULT NULL,
  `C_MARGIN_LOAN` decimal(20, 0) DEFAULT NULL,
  `C_MARGIN_PLUS_LOAN` decimal(20, 0) DEFAULT NULL,
  `C_ADVANCE_LOAN` decimal(20, 0) DEFAULT NULL,
  `C_MARGIN_REVENUE` decimal(20, 0) DEFAULT NULL,
  `C_MARGIN_PLUS_REVENUE` decimal(20, 0) DEFAULT NULL,
  `C_ADVANCE_REVENUE` decimal(20, 0) DEFAULT NULL,
  `C_SUM_FINANCE_SERVICE_REVENUE` decimal(20, 0) DEFAULT NULL,
  `C_SUM_FINANCE_SERVICE_LOAN` decimal(20, 0) DEFAULT NULL,
  `C_FINANCE_SERVICE_CAP_EXPEND` decimal(20, 0) DEFAULT NULL,
  `C_B_REVENUE_NET_ADJUSTED` decimal(20, 0) DEFAULT NULL,
  `C_D_REVENUE_NET_ADJUSTED` decimal(20, 0) DEFAULT NULL,
  `C_SUM_FIN_SERVICE_REVENUE_NET` decimal(20, 0) DEFAULT NULL,
  `C_TOTAL_REVENUE_NET` decimal(20, 0) DEFAULT NULL,
  `C_REVENUE_NET_AVERAGE_MONTH` decimal(20, 0) DEFAULT NULL,
  `C_NET_ASSET_AVERAGE` decimal(20, 0) DEFAULT NULL,
  `C_FINANCE_MANAGED_RANKING` varchar(1048576) DEFAULT NULL,
  `C_FINANCE_ANNOUCED_RANKING` varchar(1048576) DEFAULT NULL,
  `C_NAV_ANNOUCED_RANKING` varchar(1048576) DEFAULT NULL,
  `C_SYNTHETIC_ANNOUCED_RANKING` varchar(1048576) DEFAULT NULL,
  `valid_from` datetime DEFAULT NULL,
  `valid_to` datetime DEFAULT NULL,
  `is_current` boolean DEFAULT NULL
)
PRIMARY KEY (PK_MONTHLY_DETAIL_ID, partition_year, partition_month)
PARTITION BY (partition_year, partition_month)
DISTRIBUTED BY HASH(PK_MONTHLY_DETAIL_ID) BUCKETS 4
PROPERTIES (
    "replication_num" = "2"
)

CREATE TABLE default_catalog.mbs_realtime_db.fact_t_margin_extra_balance_his (
  `C_DEFAULT_PRIMARY_KEY` varchar(1048576),
  `partition_date` date,
  `PK_MARGIN_EXTRA_BALANCE` varchar(1048576),
  `FK_MARGIN_CONTRACT` varchar(1048576) DEFAULT NULL,
  `C_ACCOUNT_CODE` varchar(1048576) DEFAULT NULL,
  `C_TRADING_DATE` datetime DEFAULT NULL,
  `C_DELIVER_DATE` datetime DEFAULT NULL,
  `C_CAPITAL_CODE` varchar(1048576) DEFAULT NULL,
  `C_DELIEVER_TYPE` varchar(1048576) DEFAULT NULL,
  `C_DELIVER_VALUE` decimal(15, 0) DEFAULT NULL,
  `C_INTEREST_RATE` decimal(15, 5) DEFAULT NULL,
  `C_INTERM_LOAN` decimal(15, 0) DEFAULT NULL,
  `C_INTERM_LOAN_OUT` decimal(15, 0) DEFAULT NULL,
  `C_INTERM_FEE` decimal(15, 0) DEFAULT NULL,
  `C_INTERM_FEE_IN` decimal(15, 0) DEFAULT NULL,
  `C_INTERM_FEE_OUT` decimal(15, 0) DEFAULT NULL,
  `C_EXPIRE_DATE` datetime DEFAULT NULL,
  `C_OUTTERM_RATE` decimal(15, 5) DEFAULT NULL,
  `C_OUTTERM_LOAN` decimal(15, 0) DEFAULT NULL,
  `C_OUTTERM_LOAN_OUT` decimal(15, 0) DEFAULT NULL,
  `C_OUTTERM_FEE` decimal(15, 0) DEFAULT NULL,
  `C_OUTTERM_FEE_IN` decimal(15, 0) DEFAULT NULL,
  `C_OUTTERM_FEE_OUT` decimal(15, 0) DEFAULT NULL,
  `C_ORIGINAL_EXPIRE_DATE` datetime DEFAULT NULL,
  `C_LAST_EXPIRE_DATE_BGEDOL` datetime DEFAULT NULL,
  `C_DELIVER_CODE` varchar(1048576) DEFAULT NULL,
  `C_DELIVER_T` decimal(38, 0) DEFAULT NULL,
  `C_INTEREST_DEBIT_TYPE` varchar(1048576) DEFAULT NULL,
  `C_SET_ORDER_TYPE` varchar(1048576) DEFAULT NULL,
  `C_INTEREST_RATE_CODE` varchar(1048576) DEFAULT NULL,
  `C_ACCOUNT_BRANCH_CODE` varchar(1048576) DEFAULT NULL,
  `C_ACCOUNT_SUB_BRANCH_CODE` varchar(1048576) DEFAULT NULL,
  `C_MARKETING_ID` varchar(1048576) DEFAULT NULL,
  `valid_from` datetime DEFAULT NULL,
  `valid_to` datetime DEFAULT NULL,
  `is_current` boolean DEFAULT NULL
)
PRIMARY KEY (C_DEFAULT_PRIMARY_KEY, partition_date)
PARTITION BY (partition_date)
DISTRIBUTED BY HASH(C_DEFAULT_PRIMARY_KEY) BUCKETS 6
PROPERTIES (
    "replication_num" = "2"
)

CREATE TABLE default_catalog.mbs_realtime_db.dim_t_list_branch_bank_adv_wdr (
  `PK_BRANCH_BANK` varchar(1048576),
  `FK_BANK_CODE` varchar(1048576) DEFAULT NULL,
  `C_BRANCH_BANK_CODE` varchar(1048576) DEFAULT NULL,
  `C_BRANCH_BANK_NAME` varchar(1048576) DEFAULT NULL,
  `C_ORDER` decimal(38, 10) DEFAULT NULL,
  `C_STATUS` decimal(38, 10) DEFAULT NULL,
  `valid_from` datetime DEFAULT NULL,
  `valid_to` datetime DEFAULT NULL,
  `is_current` boolean DEFAULT NULL
)
PRIMARY KEY (PK_BRANCH_BANK)
PROPERTIES (
    "replication_num" = "2"
)

CREATE TABLE default_catalog.mbs_realtime_db.dim_v_t_list_front_user (
  `PK_FRONT_USER` varchar(1048576),
  `partition_date` date,
  `C_BRANCH_CODE` varchar(1048576) DEFAULT NULL,
  `C_SUB_BRANCH_CODE` varchar(1048576) DEFAULT NULL,
  `C_FRONT_USER_CODE` varchar(1048576) DEFAULT NULL,
  `C_RESET_PWD_FLAG` decimal(1, 0) DEFAULT NULL,
  `C_BUSINESS_TYPE` varchar(1048576) DEFAULT NULL,
  `C_FUNC_RIGHT_GROUP` varchar(1048576) DEFAULT NULL,
  `C_DATA_RIGHT_GROUP` varchar(1048576) DEFAULT NULL,
  `C_DATA_RIGHT_LIST` varchar(1048576) DEFAULT NULL,
  `C_APPROVE_STATUS` decimal(1, 0) DEFAULT NULL,
  `C_APPROVE_CREDIT` decimal(15, 0) DEFAULT NULL,
  `C_ACCOUNT_INTERNET` varchar(1048576) DEFAULT NULL,
  `C_ENTRUST_AUTHEN_TYPE` varchar(1048576) DEFAULT NULL,
  `C_VALUE_PER_ORDER` decimal(15, 0) DEFAULT NULL,
  `C_VALUE_PER_DAY` decimal(15, 0) DEFAULT NULL,
  `C_FIXIP_FLAG` varchar(1048576) DEFAULT NULL,
  `C_IP_ASSIGNED` varchar(1048576) DEFAULT NULL,
  `C_LOCK_STATUS` decimal(1, 0) DEFAULT NULL,
  `C_EXPIRE_DATE` datetime DEFAULT NULL,
  `C_STATUS` decimal(1, 0) DEFAULT NULL,
  `C_TVOL_STATUS` decimal(2, 0) DEFAULT NULL,
  `C_ADMIN_LIST` varchar(1048576) DEFAULT NULL,
  `C_INFORMATION` varchar(1048576) DEFAULT NULL,
  `C_BROKER_TYPE` varchar(1048576) DEFAULT NULL,
  `C_MANAGER_CODE` varchar(1048576) DEFAULT NULL,
  `C_APPROVE_CREDIT_PER_DAY` decimal(15, 0) DEFAULT NULL,
  `C_DATE_CREATE` datetime DEFAULT NULL,
  `C_USER_CRM_STATUS` decimal(1, 0) DEFAULT NULL,
  `C_USER_PARDOT_STATUS` decimal(1, 0) DEFAULT NULL,
  `C_IS_INTERNAL_STAFF` decimal(1, 0) DEFAULT NULL,
  `C_STAFF_BRANCH_CODE` varchar(1048576) DEFAULT NULL,
  `C_STAFF_SUB_BRANCH_CODE` varchar(1048576) DEFAULT NULL,
  `C_STAFF_COMPANY` varchar(1048576) DEFAULT NULL,
  `C_STAFF_CODE` varchar(1048576) DEFAULT NULL,
  `C_BACK_USER_CODE` varchar(1048576) DEFAULT NULL,
  `C_CANCEL_FORCE_SELL_ORDER` decimal(1, 0) DEFAULT NULL,
  `C_USER_FO` varchar(1048576) DEFAULT NULL,
  `C_LAST_CHANGED_OTP` datetime DEFAULT NULL,
  `C_EXPERT_QUALIFIED` varchar(1048576) DEFAULT NULL,
  `C_EXPERT_STATUS` decimal(1, 0) DEFAULT NULL,
  `C_ENABLE_SUB_MKT_ID` decimal(38, 0) DEFAULT NULL,
  `C_CHANEL` varchar(1048576) DEFAULT NULL,
  `valid_from` datetime DEFAULT NULL,
  `valid_to` datetime DEFAULT NULL,
  `is_current` boolean DEFAULT NULL
)
PRIMARY KEY (PK_FRONT_USER)
PROPERTIES (
    "replication_num" = "2"
)

CREATE TABLE default_catalog.mbs_golden.back_data(
	C_ORIGIN_ACCOUNT_CODE varchar(1048576),
	C_ACCOUNT_CODE varchar(1048576),
	C_DATE datetime,
	C_MONTH tinyint(4),
	C_YEAR smallint(6),
	C_MARGIN_DEBT DECIMAL(38,0),
	C_MBLINK_DEBT DECIMAL(38,0),
	C_UTTB DECIMAL(38,10),
	C_GTGD DECIMAL(38,18),
	C_RANKING_KEY varchar(1048576),
  C_KY_KPI varchar(1048576)
)
DISTRIBUTED BY HASH(C_ORIGIN_ACCOUNT_CODE) BUCKETS 4
PROPERTIES(
	"replication_num" = "2"
)

CREATE TABLE default_catalog.mbs_golden.dim_erc_ranking(
	C_ORIGIN_ACCOUNT_CODE varchar(65533),
	C_YEAR_ADJ int,
	C_MONTH_ADJ int,
	C_SYNTHETIC_ANNOUCED_RANKING varchar(65533),
	C_RANKING_KEY varchar(65533)
)
PRIMARY KEY (C_ORIGIN_ACCOUNT_CODE, C_YEAR_ADJ, C_MONTH_ADJ, C_SYNTHETIC_ANNOUCED_RANKING)
DISTRIBUTED BY HASH(C_ORIGIN_ACCOUNT_CODE) BUCKETS 2
PROPERTIES(
	"replication_num" = "2"
)

CREATE MATERIALIZED VIEW default_catalog.mbs_realtime_db.mv_t_back_account
DISTRIBUTED BY HASH(C_ACCOUNT_CODE) BUCKETS 2
REFRESH ASYNC EVERY (INTERVAL 60 SECOND)
PROPERTIES(
	"replication_num" = "2"
)
AS
SELECT
    t.C_ACCOUNT_CODE,
    v.C_OPEN_DATE,
    t.C_ACCOUNT_BRANCH_CODE,
    t.C_CHANNEL
FROM default_catalog.mbs_realtime_db.t_back_account t
JOIN default_catalog.mbs_realtime_db.dim_v_t_back_account v
ON t.C_ACCOUNT_CODE = v.C_ACCOUNT_CODE


CREATE MATERIALIZED VIEW default_catalog.mbs_realtime_db.mv_dim_erc_ranking
DISTRIBUTED BY HASH(C_ORIGIN_ACCOUNT_CODE) BUCKETS 2
REFRESH ASYNC EVERY (INTERVAL 60 SECOND)
PROPERTIES(
	"replication_num" = "2"
)
AS
with adjusted_erc as (
	SELECT
		DISTINCT 
		C_ORIGIN_ACCOUNT_CODE,
		CASE
			WHEN C_MONTH = 12 THEN C_YEAR + 1
			ELSE C_YEAR
		END AS C_YEAR_ADJ,
		CASE
			WHEN C_MONTH = 12 THEN 1
			ELSE C_MONTH + 1
		END AS C_MONTH_ADJ,
		C_SYNTHETIC_ANNOUCED_RANKING
	FROM
		default_catalog.mbs_realtime_db.fact_v_t_erc_monthly_detail
)
SELECT
	*,
	CONCAT(C_ORIGIN_ACCOUNT_CODE, '_', C_YEAR_ADJ, '_', C_MONTH_ADJ) AS C_RANKING_KEY
FROM adjusted_erc   

CREATE MATERIALIZED VIEW default_catalog.mbs_realtime_db.mv_back_data
DISTRIBUTED BY HASH(C_ORIGIN_ACCOUNT_CODE) BUCKETS 2
REFRESH ASYNC EVERY (INTERVAL 60 SECOND)
PROPERTIES(
	"replication_num" = "2"
)
AS
WITH 
	margin_balance_hist AS (
	SELECT
			C_ACCOUNT_CODE,
			C_TRADING_DATE AS C_DATE,
			MONTH(C_TRADING_DATE) AS C_MONTH,
		YEAR(C_TRADING_DATE) AS C_YEAR,
		SUM(C_INTERM_LOAN - C_INTERM_LOAN_OUT + C_OUTTERM_LOAN - C_OUTTERM_LOAN_OUT) AS C_MARGIN_DEBT
	FROM
		default_catalog.mbs_realtime_db.fact_t_margin_extra_balance_his 
	GROUP BY
		C_ACCOUNT_CODE,
		C_TRADING_DATE
	),
	tlo_balance_hist AS (
	SELECT 
			C_ACCOUNT_CODE,
			C_TRANSACTION_DATE AS C_DATE,
			MONTH(C_TRANSACTION_DATE) AS C_MONTH,
		YEAR(C_TRANSACTION_DATE) AS C_YEAR,
			SUM(C_INTERM_BALANCE - C_INTERM_CASH_OUT + C_OUTTERM_BALANCE - C_OUTTERM_CASH_OUT + C_MBS_EXPIRE_DEBIT - C_TLO_COL_1) AS C_MBLINK_DEBT
	FROM
		default_catalog.mbs_realtime_db.fact_t_tlo_debit_balance_history
	GROUP BY
		C_ACCOUNT_CODE,
		C_TRANSACTION_DATE
	),
	back_adv_withdraw AS (
	SELECT 
			C_ACCOUNT_CODE,
			C_WITHDRAW_DATE AS C_DATE,
			MONTH(C_WITHDRAW_DATE) AS C_MONTH,
		YEAR(C_WITHDRAW_DATE) AS C_YEAR,
			SUM(C_CASH_VOLUME) AS C_UTTB
	FROM
		default_catalog.mbs_realtime_db.fact_t_back_advance_withdraw
	GROUP BY
		C_ACCOUNT_CODE,
		C_WITHDRAW_DATE
	),
	back_deal_history AS (
	SELECT
			C_ACCOUNT_CODE,
			C_TRANSACTION_DATE AS C_DATE,
			MONTH(C_TRANSACTION_DATE) AS C_MONTH,
		YEAR(C_TRANSACTION_DATE) AS C_YEAR,
		SUM(C_MATCHED_PRICE * C_MATCHED_VOLUME) AS C_GTGD
	FROM
		default_catalog.mbs_realtime_db.fact_t_back_deal_history
	GROUP BY
		C_ACCOUNT_CODE,
		C_TRANSACTION_DATE
	),
	OUTER_TABLE as (
	SELECT
		COALESCE(m.C_ACCOUNT_CODE, t.C_ACCOUNT_CODE, b.C_ACCOUNT_CODE, d.C_ACCOUNT_CODE) AS C_ACCOUNT_CODE,
		COALESCE(m.C_DATE, t.C_DATE, b.C_DATE, d.C_DATE) AS C_DATE,
		COALESCE(m.C_MONTH, t.C_MONTH, b.C_MONTH, d.C_MONTH) AS C_MONTH,
		COALESCE(m.C_YEAR, t.C_YEAR, b.C_YEAR, d.C_YEAR) AS C_YEAR,
		COALESCE(m.C_MARGIN_DEBT, 0) AS C_MARGIN_DEBT,
		COALESCE(t.C_MBLINK_DEBT, 0) AS C_MBLINK_DEBT,
		COALESCE(b.C_UTTB, 0) AS C_UTTB,
		COALESCE(d.C_GTGD, 0) AS C_GTGD,
		CONCAT(
			LEFT(COALESCE(m.C_ACCOUNT_CODE, t.C_ACCOUNT_CODE, b.C_ACCOUNT_CODE, d.C_ACCOUNT_CODE), 6),
			'_',
			COALESCE(m.C_YEAR, t.C_YEAR, b.C_YEAR, d.C_YEAR),
			'_',
			COALESCE(m.C_MONTH, t.C_MONTH, b.C_MONTH, d.C_MONTH)
		) AS C_RANKING_KEY
	FROM
		margin_balance_hist m
	FULL OUTER JOIN tlo_balance_hist t 
		ON 
			m.C_ACCOUNT_CODE = t.C_ACCOUNT_CODE 
			AND m.C_DATE = t.C_DATE
	FULL OUTER JOIN back_adv_withdraw b 
		ON 
			COALESCE(m.C_ACCOUNT_CODE, t.C_ACCOUNT_CODE) = b.C_ACCOUNT_CODE 
			AND COALESCE(m.C_DATE, t.C_DATE) = b.C_DATE
	FULL OUTER JOIN back_deal_history d 
		ON 
			COALESCE(m.C_ACCOUNT_CODE, t.C_ACCOUNT_CODE, b.C_ACCOUNT_CODE) = d.C_ACCOUNT_CODE
			AND COALESCE(m.C_DATE, t.C_DATE, b.C_DATE) = d.C_DATE
	)
	SELECT
		ot.*,
		LEFT(C_ACCOUNT_CODE, 6) AS C_ORIGIN_ACCOUNT_CODE,
		CASE
			WHEN C_MONTH BETWEEN 1 AND 6 THEN CONCAT(C_YEAR, ' Ky 1')
			ELSE CONCAT(C_YEAR, ' Ky 2')
		END AS C_KY_KPI
	FROM
		OUTER_TABLE ot

CREATE MATERIALIZED VIEW default_catalog.mbs_realtime_db.mv_front_data
DISTRIBUTED BY HASH(C_ORIGIN_ACCOUNT_CODE) BUCKETS 2
REFRESH ASYNC EVERY (INTERVAL 60 SECOND)
PROPERTIES(
	"replication_num" = "2"
)
AS
SELECT
	C_ACCOUNT_CODE,
	LEFT(C_ACCOUNT_CODE, 6) AS C_ORIGIN_ACCOUNT_CODE,
	DATE(CONVERT_TZ(NOW(), @@time_zone, 'Asia/Ho_Chi_Minh')) as C_DATE,
	MONTH(DATE(CONVERT_TZ(NOW(), @@time_zone, 'Asia/Ho_Chi_Minh'))) as C_MONTH,
	YEAR(DATE(CONVERT_TZ(NOW(), @@time_zone, 'Asia/Ho_Chi_Minh'))) as C_YEAR,
	0 AS C_MARGIN_DEBT,
	0 AS C_MBLINK_DEBT,
	0 AS C_UTTB,
	SUM(C_MATCHED_PRICE * C_MATCHED_VOLUME) AS C_GTGD,
	CONCAT(LEFT(C_ACCOUNT_CODE, 6), '_', YEAR(DATE(CONVERT_TZ(NOW(), @@time_zone, 'Asia/Ho_Chi_Minh'))), '_', MONTH(DATE(CONVERT_TZ(NOW(), @@time_zone, 'Asia/Ho_Chi_Minh')))) AS C_RANKING_KEY,
	CASE
        WHEN ((month(date(convert_tz(now(), @@time_zone, 'Asia/Ho_Chi_Minh')))) BETWEEN 1 AND 6) THEN (concat(year(date(convert_tz(now(), @@time_zone, 'Asia/Ho_Chi_Minh'))), ' Ky 1'))
        ELSE (concat(year(date(convert_tz(now(), @@time_zone, 'Asia/Ho_Chi_Minh'))), ' Ky 2'))
    END AS `C_KY_KPI`
FROM default_catalog.mbs_realtime_db.mv_t_front_deal
GROUP BY C_ACCOUNT_CODE, C_DATE;